insert into questions.subdirectories (id, FirstClassName, SubClassName, parentdirectory, subClassId, measureId, frequencyId) values (1, null, 'Unsweetened cereals', 1, null, null, null);
insert into questions.subdirectories (id, FirstClassName, SubClassName, parentdirectory, subClassId, measureId, frequencyId) values (2, null, 'Sweetened cereals', 1, null, null, null);
insert into questions.subdirectories (id, FirstClassName, SubClassName, parentdirectory, subClassId, measureId, frequencyId) values (3, null, 'Ready Brek or porridge', 1, null, null, null);
insert into questions.subdirectories (id, FirstClassName, SubClassName, parentdirectory, subClassId, measureId, frequencyId) values (4, null, 'Muesli', 1, null, null, null);
insert into questions.subdirectories (id, FirstClassName, SubClassName, parentdirectory, subClassId, measureId, frequencyId) values (5, null, 'White bread or rolls', 2, null, null, null);
insert into questions.subdirectories (id, FirstClassName, SubClassName, parentdirectory, subClassId, measureId, frequencyId) values (6, null, 'Brown or grannary bread or rolls', 2, null, null, null);
insert into questions.subdirectories (id, FirstClassName, SubClassName, parentdirectory, subClassId, measureId, frequencyId) values (7, null, 'Croissants,garlic bread or Aberdeen rolls', 2, null, null, null);
insert into questions.subdirectories (id, FirstClassName, SubClassName, parentdirectory, subClassId, measureId, frequencyId) values (8, null, 'Other breads(pitta, naan,tortilla,bagel)', 2, null, null, null);
insert into questions.subdirectories (id, FirstClassName, SubClassName, parentdirectory, subClassId, measureId, frequencyId) values (9, null, 'Full fat cow’s milk', 3, null, null, null);
insert into questions.subdirectories (id, FirstClassName, SubClassName, parentdirectory, subClassId, measureId, frequencyId) values (10, null, 'Semi-skimmed cow’s milk', 3, null, null, null);
insert into questions.subdirectories (id, FirstClassName, SubClassName, parentdirectory, subClassId, measureId, frequencyId) values (11, null, 'Skimmed cow’s milk', 3, null, null, null);
insert into questions.subdirectories (id, FirstClassName, SubClassName, parentdirectory, subClassId, measureId, frequencyId) values (12, null, 'Soya milk', 3, null, null, null);
insert into questions.subdirectories (id, FirstClassName, SubClassName, parentdirectory, subClassId, measureId, frequencyId) values (13, null, 'Flavoured milk(chocolate,strawberry)', 3, null, null, null);
insert into questions.subdirectories (id, FirstClassName, SubClassName, parentdirectory, subClassId, measureId, frequencyId) values (15, null, 'Drinking yogurts (Actimel, 
Yakult )', 4, null, null, null);
insert into questions.subdirectories (id, FirstClassName, SubClassName, parentdirectory, subClassId, measureId, frequencyId) values (16, null, 'Flavoured yogurts 
(e.g. all fruit yogurts, 
Crunch Corners, Crunchie Fromage frais (all flavours)', 4, null, null, null);
insert into questions.subdirectories (id, FirstClassName, SubClassName, parentdirectory, subClassId, measureId, frequencyId) values (17, null, 'Natural, low fat or low 
calorie yogurt', 4, null, null, null);
insert into questions.subdirectories (id, FirstClassName, SubClassName, parentdirectory, subClassId, measureId, frequencyId) values (18, null, 'Cream (all types)', 4, null, null, null);
insert into questions.subdirectories (id, FirstClassName, SubClassName, parentdirectory, subClassId, measureId, frequencyId) values (19, null, 'Full fat cream cheese (e.g. Philadelphia)', 4, null, null, null);
insert into questions.subdirectories (id, FirstClassName, SubClassName, parentdirectory, subClassId, measureId, frequencyId) values (20, null, 'Cheddar-type cheese 
(including Cheese strings)', 4, null, null, null);
insert into questions.subdirectories (id, FirstClassName, SubClassName, parentdirectory, subClassId, measureId, frequencyId) values (21, null, 'Low fat hard or soft cheese', 4, null, null, null);
insert into questions.subdirectories (id, FirstClassName, SubClassName, parentdirectory, subClassId, measureId, frequencyId) values (22, null, 'Eggs (boiled, fried, 
scrambled or omelette)', 4, null, null, null);
insert into questions.subdirectories (id, FirstClassName, SubClassName, parentdirectory, subClassId, measureId, frequencyId) values (23, null, 'Crisps(e.g. Walkers Crisps)', 5, null, null, null);
insert into questions.subdirectories (id, FirstClassName, SubClassName, parentdirectory, subClassId, measureId, frequencyId) values (24, null, 'walnuts', 5, null, null, null);
insert into questions.subdirectories (id, FirstClassName, SubClassName, parentdirectory, subClassId, measureId, frequencyId) values (25, null, 'Meat snacks(e.g. biltong)', 5, null, null, null);
insert into questions.subdirectories (id, FirstClassName, SubClassName, parentdirectory, subClassId, measureId, frequencyId) values (26, null, 'Nuts(e.g. peanuts, walnuts, Cashew )', 5, null, null, null);
insert into questions.subdirectories (id, FirstClassName, SubClassName, parentdirectory, subClassId, measureId, frequencyId) values (27, null, 'Dried fruit(e.g.  dried mango, dried apricots)', 5, null, null, null);
insert into questions.subdirectories (id, FirstClassName, SubClassName, parentdirectory, subClassId, measureId, frequencyId) values (28, null, 'Whole Cake(e.g. Lemon Loaf cake)', 6, null, null, null);
insert into questions.subdirectories (id, FirstClassName, SubClassName, parentdirectory, subClassId, measureId, frequencyId) values (29, null, 'Cake slices(e.g. Mini Rolls Milk Chocolate)', 6, null, null, null);
insert into questions.subdirectories (id, FirstClassName, SubClassName, parentdirectory, subClassId, measureId, frequencyId) values (30, null, 'Tarts', 6, null, null, null);
insert into questions.subdirectories (id, FirstClassName, SubClassName, parentdirectory, subClassId, measureId, frequencyId) values (31, null, 'Bananas', 7, null, null, null);
insert into questions.subdirectories (id, FirstClassName, SubClassName, parentdirectory, subClassId, measureId, frequencyId) values (32, null, 'Strawberries', 7, null, null, null);
insert into questions.subdirectories (id, FirstClassName, SubClassName, parentdirectory, subClassId, measureId, frequencyId) values (33, null, 'Pomegranate', 7, null, null, null);
insert into questions.subdirectories (id, FirstClassName, SubClassName, parentdirectory, subClassId, measureId, frequencyId) values (34, null, 'Avocados', 7, null, null, null);
insert into questions.subdirectories (id, FirstClassName, SubClassName, parentdirectory, subClassId, measureId, frequencyId) values (35, null, 'Blueberries', 7, null, null, null);
insert into questions.subdirectories (id, FirstClassName, SubClassName, parentdirectory, subClassId, measureId, frequencyId) values (36, null, 'Lemons', 7, null, null, null);
insert into questions.subdirectories (id, FirstClassName, SubClassName, parentdirectory, subClassId, measureId, frequencyId) values (37, null, 'Mango', 7, null, null, null);
insert into questions.subdirectories (id, FirstClassName, SubClassName, parentdirectory, subClassId, measureId, frequencyId) values (38, null, 'Apples', 7, null, null, null);
insert into questions.subdirectories (id, FirstClassName, SubClassName, parentdirectory, subClassId, measureId, frequencyId) values (39, null, 'Beef', 8, null, null, null);
insert into questions.subdirectories (id, FirstClassName, SubClassName, parentdirectory, subClassId, measureId, frequencyId) values (40, null, 'Lamb', 8, null, null, null);
insert into questions.subdirectories (id, FirstClassName, SubClassName, parentdirectory, subClassId, measureId, frequencyId) values (41, null, 'Pork Fillet', 8, null, null, null);
insert into questions.subdirectories (id, FirstClassName, SubClassName, parentdirectory, subClassId, measureId, frequencyId) values (42, null, 'Pork Joint', 8, null, null, null);
insert into questions.subdirectories (id, FirstClassName, SubClassName, parentdirectory, subClassId, measureId, frequencyId) values (43, null, 'Sausages', 8, null, null, null);
insert into questions.subdirectories (id, FirstClassName, SubClassName, parentdirectory, subClassId, measureId, frequencyId) values (44, null, 'Bacon', 8, null, null, null);
insert into questions.subdirectories (id, FirstClassName, SubClassName, parentdirectory, subClassId, measureId, frequencyId) values (45, null, 'Gammon', 8, null, null, null);
insert into questions.subdirectories (id, FirstClassName, SubClassName, parentdirectory, subClassId, measureId, frequencyId) values (46, null, 'Organic', 8, null, null, null);
insert into questions.subdirectories (id, FirstClassName, SubClassName, parentdirectory, subClassId, measureId, frequencyId) values (47, null, 'Smoked Salmon', 9, null, null, null);
insert into questions.subdirectories (id, FirstClassName, SubClassName, parentdirectory, subClassId, measureId, frequencyId) values (48, null, 'Fried fish', 9, null, null, null);
insert into questions.subdirectories (id, FirstClassName, SubClassName, parentdirectory, subClassId, measureId, frequencyId) values (49, null, 'Prawns', 9, null, null, null);
insert into questions.subdirectories (id, FirstClassName, SubClassName, parentdirectory, subClassId, measureId, frequencyId) values (50, null, 'Mussels with cream', 9, null, null, null);
insert into questions.subdirectories (id, FirstClassName, SubClassName, parentdirectory, subClassId, measureId, frequencyId) values (51, null, 'BBQ fish', 9, null, null, null);
insert into questions.subdirectories (id, FirstClassName, SubClassName, parentdirectory, subClassId, measureId, frequencyId) values (52, null, 'Tomatoes', 10, null, null, null);
insert into questions.subdirectories (id, FirstClassName, SubClassName, parentdirectory, subClassId, measureId, frequencyId) values (53, null, 'Potatoes', 10, null, null, null);
insert into questions.subdirectories (id, FirstClassName, SubClassName, parentdirectory, subClassId, measureId, frequencyId) values (54, null, 'Carrots', 10, null, null, null);
insert into questions.subdirectories (id, FirstClassName, SubClassName, parentdirectory, subClassId, measureId, frequencyId) values (55, null, 'Broccoli', 10, null, null, null);
insert into questions.subdirectories (id, FirstClassName, SubClassName, parentdirectory, subClassId, measureId, frequencyId) values (56, null, 'Sweetcorn', 10, null, null, null);
insert into questions.subdirectories (id, FirstClassName, SubClassName, parentdirectory, subClassId, measureId, frequencyId) values (57, null, 'squash', 10, null, null, null);
insert into questions.subdirectories (id, FirstClassName, SubClassName, parentdirectory, subClassId, measureId, frequencyId) values (58, null, 'peppers', 10, null, null, null);
insert into questions.subdirectories (id, FirstClassName, SubClassName, parentdirectory, subClassId, measureId, frequencyId) values (59, null, 'aubergines', 10, null, null, null);
insert into questions.subdirectories (id, FirstClassName, SubClassName, parentdirectory, subClassId, measureId, frequencyId) values (60, null, 'Mix salad(e.g. Babyleaf Salad, lettuce)', 10, null, null, null);
insert into questions.subdirectories (id, FirstClassName, SubClassName, parentdirectory, subClassId, measureId, frequencyId) values (61, null, 'macaroni cheese', 11, null, null, null);
insert into questions.subdirectories (id, FirstClassName, SubClassName, parentdirectory, subClassId, measureId, frequencyId) values (62, null, 'Pizza(e.g. Pepperoni Pizza, Mascarpone Pizza)', 11, null, null, null);
insert into questions.subdirectories (id, FirstClassName, SubClassName, parentdirectory, subClassId, measureId, frequencyId) values (63, null, 'Pie(e.g. fish, beef, fruit)', 11, null, null, null);
insert into questions.subdirectories (id, FirstClassName, SubClassName, parentdirectory, subClassId, measureId, frequencyId) values (64, null, 'Rice(e.g. Fied rice, chicken rice)', 11, null, null, null);
insert into questions.subdirectories (id, FirstClassName, SubClassName, parentdirectory, subClassId, measureId, frequencyId) values (65, null, 'Frozen ready meals(e.g.Cod dinner, Spaghetti Bolognese)', 11, null, null, null);
insert into questions.subdirectories (id, FirstClassName, SubClassName, parentdirectory, subClassId, measureId, frequencyId) values (66, null, 'Roast chicken', 12, null, null, null);
insert into questions.subdirectories (id, FirstClassName, SubClassName, parentdirectory, subClassId, measureId, frequencyId) values (67, null, 'Fish burger', 12, null, null, null);
insert into questions.subdirectories (id, FirstClassName, SubClassName, parentdirectory, subClassId, measureId, frequencyId) values (68, null, 'Beef burger', 12, null, null, null);
insert into questions.subdirectories (id, FirstClassName, SubClassName, parentdirectory, subClassId, measureId, frequencyId) values (69, null, 'Chicken burger', 12, null, null, null);
insert into questions.subdirectories (id, FirstClassName, SubClassName, parentdirectory, subClassId, measureId, frequencyId) values (70, null, 'Sandwich', 12, null, null, null);
insert into questions.subdirectories (id, FirstClassName, SubClassName, parentdirectory, subClassId, measureId, frequencyId) values (71, null, 'Pure fruit juice(orange, apple)', 13, null, null, null);
insert into questions.subdirectories (id, FirstClassName, SubClassName, parentdirectory, subClassId, measureId, frequencyId) values (72, null, 'Tomato juice', 13, null, null, null);
insert into questions.subdirectories (id, FirstClassName, SubClassName, parentdirectory, subClassId, measureId, frequencyId) values (73, null, 'Black currant squash', 13, null, null, null);
insert into questions.subdirectories (id, FirstClassName, SubClassName, parentdirectory, subClassId, measureId, frequencyId) values (74, null, 'Other fruit squash', 13, null, null, null);
insert into questions.subdirectories (id, FirstClassName, SubClassName, parentdirectory, subClassId, measureId, frequencyId) values (75, null, 'Diet fizzy drinks(cola, lemonade)', 13, null, null, null);
insert into questions.subdirectories (id, FirstClassName, SubClassName, parentdirectory, subClassId, measureId, frequencyId) values (76, null, 'Regular fizzy drinks', 13, null, null, null);
insert into questions.subdirectories (id, FirstClassName, SubClassName, parentdirectory, subClassId, measureId, frequencyId) values (77, null, 'Mineral water', 13, null, null, null);
insert into questions.subdirectories (id, FirstClassName, SubClassName, parentdirectory, subClassId, measureId, frequencyId) values (78, null, 'Tap water', 13, null, null, null);
insert into questions.subdirectories (id, FirstClassName, SubClassName, parentdirectory, subClassId, measureId, frequencyId) values (79, null, 'Hot chocolate', 13, null, null, null);
insert into questions.subdirectories (id, FirstClassName, SubClassName, parentdirectory, subClassId, measureId, frequencyId) values (80, null, 'Horlicks or Ovaltine', 13, null, null, null);
insert into questions.subdirectories (id, FirstClassName, SubClassName, parentdirectory, subClassId, measureId, frequencyId) values (81, null, 'Low alcohol lager or beer', 14, null, null, null);
insert into questions.subdirectories (id, FirstClassName, SubClassName, parentdirectory, subClassId, measureId, frequencyId) values (82, null, 'Dark beer(Export,bitter or stout)', 14, null, null, null);
insert into questions.subdirectories (id, FirstClassName, SubClassName, parentdirectory, subClassId, measureId, frequencyId) values (83, null, 'Light beer(lager or continental beers)', 14, null, null, null);
insert into questions.subdirectories (id, FirstClassName, SubClassName, parentdirectory, subClassId, measureId, frequencyId) values (84, null, 'White wine', 14, null, null, null);
insert into questions.subdirectories (id, FirstClassName, SubClassName, parentdirectory, subClassId, measureId, frequencyId) values (85, null, 'Red wine', 14, null, null, null);
insert into questions.subdirectories (id, FirstClassName, SubClassName, parentdirectory, subClassId, measureId, frequencyId) values (86, null, 'Sherry,port', 14, null, null, null);
insert into questions.subdirectories (id, FirstClassName, SubClassName, parentdirectory, subClassId, measureId, frequencyId) values (87, null, 'Spirits or liqueurs', 14, null, null, null);
insert into questions.subdirectories (id, FirstClassName, SubClassName, parentdirectory, subClassId, measureId, frequencyId) values (88, null, 'Alcopops(Bacardi Breezer)', 14, null, null, null);
insert into questions.subdirectories (id, FirstClassName, SubClassName, parentdirectory, subClassId, measureId, frequencyId) values (89, null, 'Cider', 14, null, null, null);
