insert into questions.subclassify (id, classifyid, detail) values (1, 1, 'Unsweetened cereals');
insert into questions.subclassify (id, classifyid, detail) values (2, 1, 'Sweetened cereals');
insert into questions.subclassify (id, classifyid, detail) values (3, 1, 'Ready Brek or porridge');
insert into questions.subclassify (id, classifyid, detail) values (4, 1, 'Muesli');
insert into questions.subclassify (id, classifyid, detail) values (5, 2, 'White bread or rolls');
insert into questions.subclassify (id, classifyid, detail) values (6, 2, 'Brown or grannary bread or rolls');
insert into questions.subclassify (id, classifyid, detail) values (7, 2, 'Croissants,garlic bread or Aberdeen rolls');
insert into questions.subclassify (id, classifyid, detail) values (8, 2, 'Other breads(pitta, naan,tortilla,bagel)');
insert into questions.subclassify (id, classifyid, detail) values (9, 3, 'Full fat cow’s milk');
insert into questions.subclassify (id, classifyid, detail) values (10, 3, 'Semi-skimmed cow’s milk');
insert into questions.subclassify (id, classifyid, detail) values (11, 3, 'Skimmed cow’s milk');
insert into questions.subclassify (id, classifyid, detail) values (12, 3, 'Soya milk');
insert into questions.subclassify (id, classifyid, detail) values (13, 3, 'Flavoured milk(chocolate,strawberry)');
insert into questions.subclassify (id, classifyid, detail) values (14, 4, 'Drinking yogurts (Actimel, 
Yakult )');
insert into questions.subclassify (id, classifyid, detail) values (15, 4, 'Flavoured yogurts 
(e.g. all fruit yogurts, 
Crunch Corners, Crunchie Fromage frais (all flavours)');
insert into questions.subclassify (id, classifyid, detail) values (16, 4, 'Natural, low fat or low 
calorie yogurt');
insert into questions.subclassify (id, classifyid, detail) values (17, 4, 'Cream (all types)');
insert into questions.subclassify (id, classifyid, detail) values (18, 4, 'Full fat cream cheese (e.g. Philadelphia)');
insert into questions.subclassify (id, classifyid, detail) values (19, 4, 'Cheddar-type cheese 
(including Cheese strings)');
insert into questions.subclassify (id, classifyid, detail) values (20, 4, 'Low fat hard or soft cheese');
insert into questions.subclassify (id, classifyid, detail) values (21, 4, 'Eggs (boiled, fried, 
scrambled or omelette)');
insert into questions.subclassify (id, classifyid, detail) values (22, 5, 'Crisps(e.g. Walkers Crisps)');
insert into questions.subclassify (id, classifyid, detail) values (23, 5, 'walnuts');
insert into questions.subclassify (id, classifyid, detail) values (24, 5, 'Meat snacks(e.g. biltong)');
insert into questions.subclassify (id, classifyid, detail) values (25, 5, 'Nuts(e.g. peanuts, walnuts, Cashew )');
insert into questions.subclassify (id, classifyid, detail) values (26, 5, 'Dried fruit(e.g.  dried mango, dried apricots)');
insert into questions.subclassify (id, classifyid, detail) values (27, 6, 'Whole Cake(e.g. Lemon Loaf cake)');
insert into questions.subclassify (id, classifyid, detail) values (28, 6, 'Cake slices(e.g. Mini Rolls Milk Chocolate)');
insert into questions.subclassify (id, classifyid, detail) values (29, 6, 'Tarts');
insert into questions.subclassify (id, classifyid, detail) values (30, 7, 'Bananas');
insert into questions.subclassify (id, classifyid, detail) values (31, 7, 'Strawberries');
insert into questions.subclassify (id, classifyid, detail) values (32, 7, 'Pomegranate');
insert into questions.subclassify (id, classifyid, detail) values (33, 7, 'Avocados');
insert into questions.subclassify (id, classifyid, detail) values (34, 7, 'Blueberries');
insert into questions.subclassify (id, classifyid, detail) values (35, 7, 'Lemons');
insert into questions.subclassify (id, classifyid, detail) values (36, 7, 'Mango');
insert into questions.subclassify (id, classifyid, detail) values (37, 7, 'Apples');
insert into questions.subclassify (id, classifyid, detail) values (38, 8, 'Beef');
insert into questions.subclassify (id, classifyid, detail) values (39, 8, 'Lamb');
insert into questions.subclassify (id, classifyid, detail) values (40, 8, 'Pork Fillet');
insert into questions.subclassify (id, classifyid, detail) values (41, 8, 'Pork Joint');
insert into questions.subclassify (id, classifyid, detail) values (42, 8, 'Sausages');
insert into questions.subclassify (id, classifyid, detail) values (43, 8, 'Bacon');
insert into questions.subclassify (id, classifyid, detail) values (44, 8, 'Gammon');
insert into questions.subclassify (id, classifyid, detail) values (45, 8, 'Organic');
insert into questions.subclassify (id, classifyid, detail) values (46, 9, 'Smoked Salmon');
insert into questions.subclassify (id, classifyid, detail) values (47, 9, 'Fried fish');
insert into questions.subclassify (id, classifyid, detail) values (48, 9, 'Prawns');
insert into questions.subclassify (id, classifyid, detail) values (49, 9, 'Mussels with cream');
insert into questions.subclassify (id, classifyid, detail) values (50, 9, 'BBQ fish');
insert into questions.subclassify (id, classifyid, detail) values (51, 10, 'Tomatoes');
insert into questions.subclassify (id, classifyid, detail) values (52, 10, 'Potatoes');
insert into questions.subclassify (id, classifyid, detail) values (53, 10, 'Carrots');
insert into questions.subclassify (id, classifyid, detail) values (54, 10, 'Broccoli');
insert into questions.subclassify (id, classifyid, detail) values (55, 10, 'Sweetcorn');
insert into questions.subclassify (id, classifyid, detail) values (56, 10, 'squash');
insert into questions.subclassify (id, classifyid, detail) values (57, 10, 'peppers');
insert into questions.subclassify (id, classifyid, detail) values (58, 10, 'aubergines');
insert into questions.subclassify (id, classifyid, detail) values (59, 10, 'Mix salad(e.g. Babyleaf Salad, lettuce)');
insert into questions.subclassify (id, classifyid, detail) values (60, 11, 'macaroni cheese');
insert into questions.subclassify (id, classifyid, detail) values (61, 11, 'Pizza(e.g. Pepperoni Pizza, Mascarpone Pizza)');
insert into questions.subclassify (id, classifyid, detail) values (62, 11, 'Pie(e.g. fish, beef, fruit)');
insert into questions.subclassify (id, classifyid, detail) values (63, 11, 'Rice(e.g. Fied rice, chicken rice)');
insert into questions.subclassify (id, classifyid, detail) values (64, 11, 'Frozen ready meals(e.g.Cod dinner, Spaghetti Bolognese)');
insert into questions.subclassify (id, classifyid, detail) values (65, 12, 'Roast chicken');
insert into questions.subclassify (id, classifyid, detail) values (66, 12, 'Fish burger');
insert into questions.subclassify (id, classifyid, detail) values (67, 12, 'Beef burger');
insert into questions.subclassify (id, classifyid, detail) values (68, 12, 'Chicken burger');
insert into questions.subclassify (id, classifyid, detail) values (69, 12, 'Sandwich');
insert into questions.subclassify (id, classifyid, detail) values (70, 13, 'Pure fruit juice(orange, apple)');
insert into questions.subclassify (id, classifyid, detail) values (71, 13, 'Tomato juice');
insert into questions.subclassify (id, classifyid, detail) values (72, 13, 'Black currant squash');
insert into questions.subclassify (id, classifyid, detail) values (73, 13, 'Other fruit squash');
insert into questions.subclassify (id, classifyid, detail) values (74, 13, 'Diet fizzy drinks(cola, lemonade)');
insert into questions.subclassify (id, classifyid, detail) values (75, 13, 'Regular fizzy drinks');
insert into questions.subclassify (id, classifyid, detail) values (76, 13, 'Mineral water');
insert into questions.subclassify (id, classifyid, detail) values (77, 13, 'Tap water');
insert into questions.subclassify (id, classifyid, detail) values (78, 13, 'Hot chocolate');
insert into questions.subclassify (id, classifyid, detail) values (79, 13, 'Horlicks or Ovaltine');
insert into questions.subclassify (id, classifyid, detail) values (80, 14, 'Low alcohol lager or beer');
insert into questions.subclassify (id, classifyid, detail) values (81, 14, 'Dark beer(Export,bitter or stout)');
insert into questions.subclassify (id, classifyid, detail) values (82, 14, 'Light beer(lager or continental beers)');
insert into questions.subclassify (id, classifyid, detail) values (83, 14, 'White wine');
insert into questions.subclassify (id, classifyid, detail) values (84, 14, 'Red wine');
insert into questions.subclassify (id, classifyid, detail) values (85, 14, 'Sherry,port');
insert into questions.subclassify (id, classifyid, detail) values (86, 14, 'Spirits or liqueurs');
insert into questions.subclassify (id, classifyid, detail) values (87, 14, 'Alcopops(Bacardi Breezer)');
insert into questions.subclassify (id, classifyid, detail) values (88, 14, 'Cider');
